# Generated by Django 5.2.16 on 2026-07-24 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngRadar_Website', '0009_ngrok_endpoint'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS filemeta (
                    dirhash BIGINT,
                    name VARCHAR(65535),
                    directory VARCHAR(65535),
                    meta BYTEA,
                    PRIMARY KEY (dirhash, name)
                );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
