# Generated by Django 5.2.17 on 2026-08-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngRadar_Website', '0012_dsocevent_message_observatoryevent_message_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE "ngRadar_Website_etransferevent"
                RENAME TO "ngRadar_Website_statusevent";
            """,
            reverse_sql="""
                ALTER TABLE "ngRadar_Website_statusevent"
                RENAME TO "ngRadar_Website_etransferevent";
            """,
        ),
        migrations.DeleteModel(
            name='ngrok_endpoint',
        ),
        migrations.RenameIndex(
            model_name='statusevent',
            new_name='ngRadar_Web_transfe_ed8eb2_idx',
            old_name='ngRadar_Web_transfe_c5bd1e_idx',
        ),
        migrations.AddField(
            model_name='statusevent',
            name='ui_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='uievent',
            name='message',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='uievent',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ready'), (2, 'Queued'), (3, 'Blocked'), (4, 'Transferring'), (5, 'Verifying'), (6, 'Transferred'), (7, 'Failed'), (8, 'Completed')], default=1),
            preserve_default=False,
        ),
    ]
