# Generated by Django 5.2.17 on 2026-08-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngRadar_Website', '0013_delete_ngrok_endpoint_and_more'),

    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE "ngRadar_Website_etransferevent"
                RENAME TO "ngRadar_Website_statusevent";
            """,
            reverse_sql="""
                ALTER TABLE "ngRadar_Website_statusevent"
                RENAME TO "ngRadar_Website_etransferevent";
            """,
        ),
        migrations.AddField(
            model_name='uievent',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
