# Generated by Django 6.1 on 2026-09-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngRadar_Website', '0015_delete_dsocevent_delete_etransferevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observatoryevent',
            name='waveform_requester',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='observatoryevent',
            name='rcvr_station',
            field=models.IntegerField(blank=True, choices=[(9, 'Green Bank (100-m, GBT)'), (90, 'St. Croix (25-m, VLBA)'), (91, 'Hancock (25-m, VLBA)'), (92, 'North Liberty (25-m, VLBA)'), (93, 'Fort Davis (25-m, VLBA)'), (94, 'Los Alamos (25-m, VLBA)'), (95, 'Pie Town (25-m, VLBA)'), (96, 'Kitt Peak (25-m, VLBA)'), (97, 'Owens Valley (25-m, VLBA)'), (98, 'Brewster (25-m, VLBA)'), (99, 'Mauna Kea (25-m, VLBA)'), (100, 'DSOC (Domenici Socorro Operations Center)'), (101, 'User Interface'), (102, 'Progress Tracking Worker')], null=True),
        ),
        migrations.AlterField(
            model_name='observatoryevent',
            name='station',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(9, 'Green Bank (100-m, GBT)'), (90, 'St. Croix (25-m, VLBA)'), (91, 'Hancock (25-m, VLBA)'), (92, 'North Liberty (25-m, VLBA)'), (93, 'Fort Davis (25-m, VLBA)'), (94, 'Los Alamos (25-m, VLBA)'), (95, 'Pie Town (25-m, VLBA)'), (96, 'Kitt Peak (25-m, VLBA)'), (97, 'Owens Valley (25-m, VLBA)'), (98, 'Brewster (25-m, VLBA)'), (99, 'Mauna Kea (25-m, VLBA)'), (100, 'DSOC (Domenici Socorro Operations Center)'), (101, 'User Interface'), (102, 'Progress Tracking Worker')], default=9, null=True),
        ),
        migrations.AlterField(
            model_name='observatoryevent',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ready'), (2, 'Queued'), (3, 'Blocked'), (4, 'Transferring'), (5, 'Verifying'), (6, 'Transferred'), (7, 'Verified'), (8, 'Failed'), (9, 'Completed'), (10, 'Polling SeaweedFS'), (11, 'Retrying storage check')], null=True),
        ),
        migrations.AlterField(
            model_name='observatoryevent',
            name='xmit_station',
            field=models.IntegerField(blank=True, choices=[(9, 'Green Bank (100-m, GBT)'), (90, 'St. Croix (25-m, VLBA)'), (91, 'Hancock (25-m, VLBA)'), (92, 'North Liberty (25-m, VLBA)'), (93, 'Fort Davis (25-m, VLBA)'), (94, 'Los Alamos (25-m, VLBA)'), (95, 'Pie Town (25-m, VLBA)'), (96, 'Kitt Peak (25-m, VLBA)'), (97, 'Owens Valley (25-m, VLBA)'), (98, 'Brewster (25-m, VLBA)'), (99, 'Mauna Kea (25-m, VLBA)'), (100, 'DSOC (Domenici Socorro Operations Center)'), (101, 'User Interface'), (102, 'Progress Tracking Worker')], null=True),
        ),
    ]
